# Generated by Django 2.2.1 on 2019-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(max_length=20, unique=True)),
                ('patient_alternative_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(blank=True, max_length=50)),
                ('patient_address', models.TextField()),
                ('patient_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
