# Generated by Django 2.2.1 on 2019-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
