# Generated by Django 2.2.1 on 2019-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_auto_20190601_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
