# Generated by Django 2.2.1 on 2019-08-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0003_auto_20190817_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_alternative_phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_status',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
