# Generated by Django 2.1.7 on 2019-10-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0004_auto_20190818_0347'),
        ('backend_main', '0003_medicinesellmodel_selldetialsmodel'),
    ]

    operations = [
    ]
