# Generated by Django 2.1.7 on 2019-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0005_merge_20191004_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_alternative_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='selldetialsmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
