# Generated by Django 2.2.5 on 2019-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0006_auto_20191004_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=14)),
                ('company_logo', models.ImageField(upload_to='setup/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
