# Generated by Django 2.2.5 on 2019-10-09 04:00

import backend_main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0007_setupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='company_logo',
            field=models.ImageField(upload_to='setup/', validators=[backend_main.validators.validate_file_extension]),
        ),
    ]
