# Generated by Django 2.2.5 on 2019-10-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0008_auto_20191009_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='company_logo',
            field=models.ImageField(upload_to='setup/'),
        ),
    ]
